extends: airbnb
env:
  mocha: true
  node: true
plugins:
  - import
  - react
  - jsx-a11y
rules:
  global-require: 0
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  comma-dangle:
    - error
    - never
